// apps/web/src/components/app-navbar.tsx
import { Link, useLocation } from "@tanstack/react-router";

export default function AppNavbar() {
  const location = useLocation();
  return (
    <nav className="container">
      <ul>
        <li><strong>Tasks App</strong></li>
      </ul>
      <ul>
        {location.pathname !== "/" && (
          <li>
            <Link to="/">Home</Link>
          </li>
        )}
      </ul>
    </nav>
  );
}

// apps/web/src/components/AppNavbar.vue
<template>
  <nav class="container">
    <ul>
      <li><strong>Tasks App</strong></li>
    </ul>
    <ul>
      <li v-if="route.path !== '/'">
        <RouterLink to="/">Home</RouterLink>
      </li>
    </ul>
  </nav>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";

const route = useRoute();
</script>
